prefixes:
  prefix: "&eCustomBlocks&8> &7"
  warn: "&eWarning &8> &7"
gui_title: "&6Custom Blocks GUI"
blocks:
  - id: "customblocks:example"
    itemModelData: 1001
    instrument: BANJO
    note: 1
    powered: false
cb_item_material: PAPER
clickable_materials: [ DARK_OAK_WALL_SIGN, DARK_OAK_DOOR, SPRUCE_SIGN, OAK_WALL_SIGN, CRIMSON_TRAPDOOR, TRAPPED_CHEST, DARK_OAK_TRAPDOOR, WARPED_SIGN, BIRCH_TRAPDOOR, JUNGLE_DOOR, JUNGLE_TRAPDOOR, OAK_TRAPDOOR, SMITHING_TABLE, COMMAND_BLOCK, JUNGLE_SIGN, ACACIA_WALL_SIGN, JUNGLE_WALL_SIGN, CRIMSON_BUTTON, ENDER_CHEST, STONE_BUTTON, OAK_SIGN, BIRCH_SIGN, CRIMSON_SIGN, BIRCH_DOOR, BREWING_STAND, SPRUCE_WALL_SIGN, CRAFTING_TABLE, LECTERN, BIRCH_WALL_SIGN, ACACIA_DOOR, ACACIA_SIGN, WARPED_BUTTON, SPRUCE_BUTTON, ACACIA_TRAPDOOR, WARPED_DOOR, ENCHANTING_TABLE, ACACIA_BUTTON, OAK_BUTTON, BIRCH_BUTTON, SPRUCE_DOOR, REPEATING_COMMAND_BLOCK, CRIMSON_WALL_SIGN, SPRUCE_TRAPDOOR, POLISHED_BLACKSTONE_BUTTON, DARK_OAK_BUTTON, WARPED_WALL_SIGN, DARK_OAK_SIGN, CHEST, CRIMSON_DOOR, JUNGLE_BUTTON, CARTOGRAPHY_TABLE, WARPED_TRAPDOOR, OAK_DOOR, LEVER, CHAIN_COMMAND_BLOCK ]
debug_mode: false