name: CustomBlocks
version: ${project.version}
main: me.monkeykiller.customblocks.Main
api-version: 1.16
authors: [ MonkeyKiller ]
website: https://github.com/MMonkeyKiller
depend: [ NBTAPI ]

commands:
  customblocks:
    aliases: cb
    description: CustomBlocks main command
    permission: customblocks.command.customblocks
  cblocks:
    aliases: cbks
    description: Get all custom blocks
    permission: customblocks.command.cblocks

