name: CustomBlocks
version: ${project.version}
main: me.monkeykiller.customblocks.CustomBlocksPlugin
api-version: 1.16
authors: [ MonkeyKiller ]
website: https://github.com/MMonkeyKiller/CustomBlocks
depend: [ NBTAPI ]
softdepend: [ WorldEdit ]

commands:
  customblocks:
    aliases: cb
    description: CustomBlocks main command
    permission: customblocks.command.customblocks
  cblocks:
    aliases: cbks
    description: Opens a GUI containing all the registered customblocks
    permission: customblocks.command.cblocks

