prefixes:
  prefix: "&eCustomBlocks &8> &7"
  warn: "&eWarning &8> &7"
gui_title: "Custom Blocks GUI"
blocks:
  - id: "customblocks:example"
    itemModelData: 1001
    instrument: BANJO
    note: 1
    powered: false
cb_item_material: PAPER
debug_mode: false